### ISSUE TITLE
command.com: `dir/w` returns no files in MS-DOS Player after removing ioctl-check in current version, while Udo's versions work

### ISSUE THREAD

**Issue by roytam1** [SvarDOS/edrdos#19] opened 2023-12-30 02:24 UTC
commenting out https://github.com/SvarDOS/edrdos/blob/f88041e9a9921454ef2d4dba98127a56ec1a1b1b/command/com.c#L483-L490 can make DR-COMMAND.COM work on other DOS(FreeDOS tested OK, not on MS-DOS 7.1 or PC-DOS 7.1) and NTVDM/MS-DOS Player (msdos.exe).

and in MS-DOS Player, `dir/w` shows no files in current version, while it works on Udo's COMMAND.COM.

**Comment by boeckmann** [comment] 2023-12-30 14:05
Thanks for pointing this out. I‘ll try to find out which change broke it. I did not know about Ms-dos player before and will have a look at it.

**Comment by boeckmann** [comment] 2023-12-30 17:37
I can confirm that the current version shows the behaviour you described inside the MS-DOS player.

@roytam1 do you know the exact version of the last binary that works for you? Going through the commit logs, not much did change since 7.01.08 WIP, the last version from Udo. But command.com did change a lot between 7.01.06 and 7.01.08 WIP, mainly because the addition of partial long file name support.

command.com seem generally be seriously flawed. For example, autoexec is executed twice on boot. This behaviour already occurs on Udos last version 7.01.08 WIP. I did not go further back though...

**Comment by roytam1** [comment] 2023-12-30 23:42
> @roytam1 do you know the exact version of the last binary that works for you?

the last WIP I have (i.e. d110721b.zip) is still working fine here.

and binary dated 23-08-21 fails.

**Comment by boeckmann** [comment] 2024-01-01 22:12
There is a problem regarding trailing CR when COMMAND.COM reads a command line from the keyboard. Some readline functions return a trailing CR (MS-DOS player, for example). This causes problems for some internal COMMAND.COM commands. See screenshots.

DR-DOS:
![grafik](https://github.com/SvarDOS/edrdos/assets/6333969/817b1357-2722-4317-ad59-36b7318d0432)

MS-DOS player:
![grafik](https://github.com/SvarDOS/edrdos/assets/6333969/78d255e9-cf64-4578-b4f7-5c999d73e036)

**Comment by boeckmann** [comment] 2024-01-01 22:13
@roytam1 this should be fixed by 71c5aca.

**Closed** 2024-01-03 01:06 UTC
Labels: bug

**Comment by roytam1** [comment] 2024-01-03 01:17
> make DR-COMMAND.COM work on other DOS(FreeDOS tested OK, not on MS-DOS 7.1 or PC-DOS 7.1)

maybe there is a need opening another issue for MS-DOS/PC DOS compatibility.

**Comment by boeckmann** [comment] 2024-01-04 11:03
> and BTW I recreated edrdos history with WIP releases. https://github.com/roytam1/edrdos

Thats rather nice. Do you plan to otherwise work on this repository or is it solely for documentation of history?

> maybe there is a need opening another issue for MS-DOS/PC DOS compatibility.

Yes we can do this, rather as a compatiblilty issue than a bug.

**Comment by roytam1** [comment] 2024-01-04 14:01
> Do you plan to otherwise work on this repository or is it solely for documentation of history?

I don't have a plan to further working on this in the moment so the repo will be for documentation right now. feel free to fork and work on it, `git format-patch 62ecda56391dc312b13c3a0d411cf9b214f22d7a...HEAD` and `git am 00*.patch` can import later changes to repo.
