### ISSUE TITLE
Division overflow on cylinder calculation

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#109] opened 2024-09-06 07:36 UTC
Willi Spiegl reported a Division Error on one of his PCs when booting the EDR kernel. I am afraid that a dump of the disk is needed to debug this, as my first guess is that it as something to do with the FAT filesystems on this PC.

![threema-20240905-233302579](https://github.com/user-attachments/assets/cb50560c-b867-493f-8f8e-2184dddec7e0)

**Comment by mateuszviste** [comment] 2024-09-06 07:57
The "Divide Error" is a message printed by the INT0 handler of EDR, so it appears the CPU performed a `div` on 0.
It's probably obvious to you, but most "risky" div operations in early stages (bdosldr) are related to BT_bytes_per_sector. I can't find where this variable is initialized, but is it verified to be non-zero?

**Comment by boeckmann** [comment] 2024-09-06 12:53
I requested Willi trying to isolate problematic partitions (by hiding them). I further requested Willi to provide a dump of specific partitions if these cause this trouble. Because without it this will be really hard to debug...

**Comment by boeckmann** [comment] 2024-09-06 12:54
Idea is that the kernel comes up with the problematic partition hidden.

**Comment by boeckmann** [comment] 2024-09-06 13:17
> The "Divide Error" is a message printed by the INT0 handler of EDR, so it appears the CPU performed a `div` on 0. It's probably obvious to you, but most "risky" div operations in early stages (bdosldr) are related to BT_bytes_per_sector. I can't find where this variable is initialized, but is it verified to be non-zero?

This particular code in bdosldr is only used by the dual-file kernel to load drdos.sys. It is not included in the single-file version. But like you said there will most probably be a

**Comment by boeckmann** [comment] 2024-09-13 11:34
I was not able to reproduce the problem with the partition dump Willi sent me by using it inside a VM. I found a few problematic code lines containing DIV in disk.asm, which can trigger an exception if max_head or max_sect are zero. These may be zero if the BIOS returns a "zero" geometry. However, a patched kernel also did not run on Willis machine. So this was not the problem in this specific case.

**Comment by boeckmann** [comment] 2024-09-13 11:36
Willi mentioned that the system works if booted from a USB stick via the image provided under http://svardos.org/?p=files&dir=20240905. But it does not work if booted from floppy using an image from the same source. I can currently not make any sense of this.

**Comment by boeckmann** [comment] 2024-09-13 12:59
> If I'm seeing this correctly these images use a zerocomp-compressed single-file SvarDOS kernel flavour, named kernel.sys, loaded to 00600h by the FreeDOS boot sector loader?

Correct.

**Comment by ecm-pushbx** [comment] 2024-09-13 18:28
I added [a small cs:ip and code dump](https://hg.pushbx.org/ecm/edrdos/rev/57bd9fc4efd9) to the int 0 handler. If the bug affects lDOS flavoured kernels as well then this build will display where the error occurs. Build is provided in https://pushbx.org/ecm/test/20240913/

**Comment by ecm-pushbx** [comment] 2024-09-13 18:46
Updated [to display the entire dump to stderr](https://hg.pushbx.org/ecm/edrdos/rev/0b2cc8420eea) instead of stdout, I'd not noticed this before.

**Comment by ecm-pushbx** [comment] 2024-09-13 18:47
https://pushbx.org/ecm/test/20240913/ now contains the most recent build from https://hg.pushbx.org/ecm/edrdos/rev/0b2cc8420eea

**Comment by boeckmann** [comment] 2024-09-13 20:33
I will try to prepare a floppy image for Willi with your kernel on weekend. Do you have an image already on your website containing lDOS bootloader, so that I only have to replace the kernel? Otherwise I will build one "from scratch"...

**Comment by ecm-pushbx** [comment] 2024-09-13 21:39
> I will try to prepare a floppy image for Willi with your kernel on weekend. Do you have an image already on your website containing lDOS bootloader, so that I only have to replace the kernel? Otherwise I will build one "from scratch"...

Several solutions:

  1. Build it like `nasm -I ~/proj/lmacros/ ~/proj/ldosboot/boot.asm -D_FAT16=0 -D_COMPAT_LDOS -D_LOAD_NAME="'EDRDOS'" -o bootedr.bin && nasm
-I ~/proj/lmacros/ ~/proj/bootimg/bootimg.asm -D_BOOTPATCHFILE="'bootedr.bin'" -D_PAYLOADFILE=::empty -o diskette.img`
  2. Get result of same in https://pushbx.org/ecm/test/20240913/diskette.img (I tested that this works if you put the files in using mcopy.)
  3. Use another loader, and rename either the kernel file (eg kernel.sys, drbio.sys, io.sys) or patch the boot loader to load this file (eg `instsect A: /BO /F1=edrdos.com`).

**Comment by boeckmann** [comment] 2024-09-14 10:03
"success" :) Screenshot attached.

![Groß (20240914_114058)](https://github.com/user-attachments/assets/10023c1b-0198-49e4-9226-5d42a06afaa9)

**Comment by boeckmann** [comment] 2024-09-14 10:21
Line causing to exception:
https://github.com/SvarDOS/edrdos/blob/3092c8ac024ed503aea946332d01b86fb7a10a98/drbio/disk.asm#L1194

**Comment by boeckmann** [comment] 2024-09-14 10:31
CX should contain sectors per cylinder. This must be zero on exception. So [UDSC.BPB+BPB.SPT] and / or [UDSC.BPB+BPB.HEADS] must be zero to trigger this. Question is where this zero comes from..

**Comment by ecm-pushbx** [comment] 2024-09-14 11:07
> "success" :) Screenshot attached.
> 
> ![Groß (20240914_114058)](https://private-user-images.githubusercontent.com/6333969/367507143-10023c1b-0198-49e4-9226-5d42a06afaa9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTA4NzEsIm5iZiI6MTcyNjMxMDU3MSwicGF0aCI6Ii82MzMzOTY5LzM2NzUwNzE0My0xMDAyM2MxYi0wMTk4LTQ5ZTQtOTIyNi01ZDQyYTA2YWZhYTkuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDEwNDI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZGM4YjdjYmI0YjNiN2YyYmZhNGE1YWViOGQ2MTUxOWU3OThhZTE0NDU3ZGEwYmJmOGRkMWVjYjk0MDViYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NyFZ_Lrdd8JNXczqW3EdsSRHYR9kkTQU6DE1ILJwZ40)

I noticed that this has the not-short version in the "starting" message. This is caused by a peculiarity of the nasm -t mode (TASM compatibility) which is needed for the @@ prefix to indicate local labels. Fixed by https://hg.pushbx.org/ecm/edrdos/rev/188410a95b70

**Comment by ecm-pushbx** [comment] 2024-09-14 11:13
Small hint for debugging: If you forgot to set "check debugger" in the lCFG block you can `boot protocol ldos edrdos.com` then `tp ffffff while cs == 200` (skip iniload operation) and then `e cs:20 + #20 2` (set assume debugger in drkernpl's lCFG block) =)

**Comment by ecm-pushbx** [comment] 2024-09-14 11:32
> CX should contain sectors per cylinder. This must be zero on exception. So [UDSC.BPB+BPB.SPT] and / or [UDSC.BPB+BPB.HEADS] must be zero to trigger this. Question is where this zero comes from..

Actually `cx` need not be zero, it could be too small as well. Like if you divide 10_0000h by 2 then the result should be 8_0000h which doesn't fit in a word register so this would also cause an int 0.

**Comment by boeckmann** [comment] 2024-09-14 12:15
@ecm-pushbx sorry, edited your commend instead of quoting :(

**Comment by boeckmann** [comment] 2024-09-14 12:16
> Actually `cx` need not be zero, it could be too small as well. Like if you divide 10_0000h by 2 then the result should be 8_0000h which doesn't fit in a word register so this would also cause an int 0.


Good hint. And this might actually be the case here. I looked again at Willis screenshot with the partition layout. The FAT32 partitions starts at around 768GB into the disk, but at 63*255*65535*512/1024/1024 ~ 514GiB the 16 bit cylinder value should overflow. Would explain why the partition dump works for me (I modified it to start at absolute sector 63 for the sake of disk space).

I will try to create a sparse disk image as large as Willis disk and create an empty FAT-32 partition at around the same start sector as his partition. Should be sufficient to reproduce the Problem if this is the cause.
 
![1680-1050-max](https://github.com/user-attachments/assets/de0fd013-d6b4-4c9c-8cc9-32e5b8374741)

**Comment by ecm-pushbx** [comment] 2024-09-14 12:31
I added a small display of the registers ax, bx, cx, dx in https://pushbx.org/ecm/test/20240914

**Comment by boeckmann** [comment] 2024-09-14 12:51
I could reproduce it under QEMU with a FAT partition starting 700GB (somewhat randomly choosen) into the disk. And a possible fix is [1b985bd](https://github.com/SvarDOS/edrdos/commit/1b985bd5a62500da51c24e3790d2d64eb9567f31). I think not calculating the CHS values on LBA enabled drives should be safe.

**Comment by ecm-pushbx** [comment] 2024-09-14 14:25
> I could reproduce it under QEMU with a FAT partition starting 700GB (somewhat randomly choosen) into the disk. And a possible fix is [1b985bd](https://github.com/SvarDOS/edrdos/commit/1b985bd5a62500da51c24e3790d2d64eb9567f31). I think not calculating the CHS values on LBA enabled drives should be safe.

Picked in https://hg.pushbx.org/ecm/edrdos/rev/5113afa906a9

**Comment by ecm-pushbx** [comment] 2024-09-14 14:50
> Willi mentioned that the system works if booted from a USB stick via the image provided under http://svardos.org/?p=files&dir=20240905. But it does not work if booted from floppy using an image from the same source. I can currently not make any sense of this.

This is still a bit of a mystery. Does the d/config.sys or something else cause an access to C: which is the FAT32 partition past 500 GiB? I don't think it should crash if there is no access done to C:

**Comment by boeckmann** [comment] 2024-09-14 15:07
This also came into my mind, and I do not have an answer yet why the kernel accesses C: at all when booting from drive A:. Perhaps there is something going on in DRDOS.SYS which causes every partition to be accessed once? Have to investigate further...

**Comment by boeckmann** [comment] 2024-09-14 15:14
No, only C: seems to be affected. If I put a C: partition in front of the partition at 700GB (which becomse D: then), the Division error is only triggered when manually selecting drive D:

**Comment by boeckmann** [comment] 2024-09-14 15:18
Follow-up issue: https://github.com/SvarDOS/edrdos/issues/112

**Closed** 2024-09-21 13:01 UTC
Labels: bug
